### ISSUE TITLE
Newest version is not posted on repository

### ISSUE THREAD

**Issue by rafi0** [zeganstyl/thelema-engine#2]
Hi,
can you please provide the newest 0.6.0 version on some repo? Please be advised, that the jcenter is deprecated. It would be a shame if you stopped working on such great software :) keep up the good work.

**Comment by zeganstyl** [comment]
Yes, yes, I will update everything, but later. For now I have some important things that I must do first.

**Comment by zeganstyl** [comment]
Libraries are uploaded to Github packages.
