### ISSUE TITLE
thelema-studio sources

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [zeganstyl/thelema-engine#4]
Are thelema-studio sources available for the public?

**Comment by zeganstyl** [comment]
Yes, you can use and modificate code. The license is Apache 2.0. And sources available here on Github.

Some assets (3d models, images in test resources) may have different license, so it is better to check them.

**Comment by zeganstyl** [comment]
Ah, you mean thelema-studio. Not yet. Later I will add code in this module.

**Comment by dmitrykolesnikovich** [comment]
How do you run studio? `gradlew thelema-studio:run` does not work.

**Comment by zeganstyl** [comment]
I run it from IDE buttons. Main class - ThelemaStudioJvm.
I will add this gradle task to thelema studio module.

**Comment by zeganstyl** [comment]
Added gradle task c804800147a8773ccaf7b08dc45461431ed8ac8c

**Comment by dmitrykolesnikovich** [comment]
I fixed running studio under MacOS target https://github.com/zeganstyl/thelema-engine/pull/9

Here is details: https://stackoverflow.com/q/60508926/909169
