### ISSUE TITLE
Github packages over maven central

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [zeganstyl/thelema-engine#5]
Some insights on why to use Github packages over traditional maven central?

**Comment by zeganstyl** [comment]
I want to use Sonatype OSSRH, but it is not so easy. I will try it when I have more free time.

**Comment by dmitrykolesnikovich** [comment]
do you mean your personal host or maven central host?

**Comment by zeganstyl** [comment]
> do you mean your personal host or maven central host?

Maven central.
