### ISSUE TITLE
native linux package

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [zeganstyl/thelema-engine#6]
Did you manage not just run test under linuxX64 target with Gradle but also make distributive package for Linux, that works natively without JDK installed? Is it possible at the moment?

**Comment by zeganstyl** [comment]
I have tried one tool, don't remember what it was, but I think it was jlink. I have created package with minified java runtime and my application. So yes, it must be possible.

**Comment by dmitrykolesnikovich** [comment]
You should try https://github.com/korlibs/korge-hello-world

There is `./gradlew linkDebugExecutableLinuxX64` task for Linux. I do not know if it works because I am using MacOS.

But I can say for sure that `./gradlew packageMacosX64AppDebug` perfectly works and generates 100% native .app bundle without JDK needed at all.

**Comment by zeganstyl** [comment]
If you mean to build Kotlin native module, in Thelema it does not work for now. There was issue:
https://youtrack.jetbrains.com/issue/KT-47061

**Comment by dmitrykolesnikovich** [comment]
Do you mean that without OpenAL everything is OK? Did you successfully managed to build runnable Kotlin native module for Linux? What about Windows?

**Comment by zeganstyl** [comment]
For MacOS I can't create Kotlin native module, because don't have Apple devices with MacOS.

**Comment by dmitrykolesnikovich** [comment]
I mean Linux and Windows

**Comment by zeganstyl** [comment]
> Do you mean that without OpenAL everything is OK? Did you successfully managed to build runnable Kotlin native module for Linux? What about Windows?

Without OpenAL not tried yet and can't say if it works or not, but I think not, because I long time not worked with native module.

When I have tried native module with old engine version, it worked on Linux. With Windows not tried.

**Comment by dmitrykolesnikovich** [comment]
Does building Kotlin native module intends to create Linux package with all binaries and resources inside? Or just files on disk?

**Comment by dmitrykolesnikovich** [comment]
FYI I finally managed to make native Windows executable (.exe) file from this sources https://github.com/TobseF/HitKlack

**Comment by zeganstyl** [comment]
> Does building Kotlin native module intends to create Linux package with all binaries and resources inside? Or just files on disk?

As I remember all resources packaging in single executable file.
You can see:
https://github.com/zeganstyl/thelema-engine/releases/tag/0.5.0

**Comment by dmitrykolesnikovich** [comment]
> > Does building Kotlin native module intends to create Linux package with all binaries and resources inside? Or just files on disk?
> 
> As I remember all resources packaging in single executable file. You can see: https://github.com/zeganstyl/thelema-engine/releases/tag/0.5.0

Problem with that is that .kexe file does not contain resources (fonts, images, etc)

**Comment by dmitrykolesnikovich** [comment]
Unlike .app file on MacOS

**Comment by dmitrykolesnikovich** [comment]
I closed issue by mistake. Reopened.

**Comment by zeganstyl** [comment]
> > Does building Kotlin native module intends to create Linux package with all binaries and resources inside? Or just files on disk?
> 
> As I remember all resources packaging in single executable file.
> You can see:
> https://github.com/zeganstyl/thelema-engine/releases/tag/0.5.0

ah, no, I wrong, it was resources in separate files.

**Comment by dmitrykolesnikovich** [comment]
> FYI I finally managed to make native Windows executable (.exe) file from this sources https://github.com/TobseF/HitKlack

By the way, by Windows native executable file I mean that you do not need JDK to run your game.

**Comment by dmitrykolesnikovich** [comment]
I write my game engine in Kotlin too that's why I am asking. https://github.com/featurea/engine

**Comment by dmitrykolesnikovich** [comment]
Problem with Linux and Windows is that unlike MacOS there is no option to bundle all the resources in one executable. You should to archive .exe file and resource files in ZIP file. 
![image](https://user-images.githubusercontent.com/6131040/138249909-76c945a9-325c-4171-a495-7b1e665f5527.png)

**Comment by dmitrykolesnikovich** [comment]
Native package for MacOS is just .app file with all resources and executables inside.

Like `build/Candy Crush-DEBUG.app` in example https://github.com/TobseF/Candy-Crush-Clone

![image](https://user-images.githubusercontent.com/6131040/138250210-88048727-1230-4515-ab5c-5ed7dc698c80.png)

**Comment by dmitrykolesnikovich** [comment]
All the logic behind native build is not Kotlin Native alone but Korge Gradle Plugin https://github.com/korlibs/korge-plugins

**Comment by zeganstyl** [comment]
Why you need all in one single executable?
But I can't right now check if it is possible to do by some gradle task. I will look when I will be at my PC.

**Comment by dmitrykolesnikovich** [comment]
> Why you need all in one single executable?

I always thought that Unity does this. But know I checked and I found out that it does not https://docs.unity3d.com/550/Documentation/Manual/PublishingBuilds.html. After you build Unity game for Windows you need to ZIP resulting .exe with resources. Never knew that. It turns out I do not need it neither then.

**Comment by dmitrykolesnikovich** [comment]
https://stackoverflow.com/a/37191456/909169

**Comment by dmitrykolesnikovich** [comment]
Yes, Unity does not make an installer for you. You have to use 3rd party software [Inno Setup](https://jrsoftware.org/isinfo.php) to make an installer by yourself https://youtu.be/7nxKAtxGSn8?t=351

**Comment by dmitrykolesnikovich** [comment]
Never knew this :)

**Comment by zeganstyl** [comment]
> Yes, Unity does not make an installer for you. You have to use 3rd party software [Inno Setup](https://jrsoftware.org/isinfo.php) to make an installer by yourself https://youtu.be/7nxKAtxGSn8?t=351

Yes, for this i used NSIS before.

**Comment by dmitrykolesnikovich** [comment]
To achieve this 100% native build author of Korge game engine just implements everything natively with importing `platform.windows.*` Kotlin package like this  https://github.com/korlibs/korgw/blob/master/korgw/src/mingwX64Main/kotlin/com/soywiz/korgw/DefaultGameWindowMingwX64.kt#L13

So, it's all simple just needs to be done.

**Comment by dmitrykolesnikovich** [comment]
> If you mean to build Kotlin native module, in Thelema it does not work for now. There was issue: https://youtrack.jetbrains.com/issue/KT-47061

You can check out how he implement Audio Library so compilation under linuxX64 platform working https://github.com/korlibs/korau

**Comment by zeganstyl** [comment]
> > If you mean to build Kotlin native module, in Thelema it does not work for now. There was issue: https://youtrack.jetbrains.com/issue/KT-47061
> 
> You can check out how he implement Audio Library so compilation under linuxX64 platform working https://github.com/korlibs/korau

Yes, he already did what I wanted to do:
- compile native lib openal that will be working with latest kotlin native
- port ogg library to Kotlin https://github.com/Gagravarr/VorbisJava

I think it is simpler to copy code from his repo )

**Comment by zeganstyl** [comment]
I disabled OpenAL code. And performed some fixes to native module.
It works now, but some features not working, for example loading gltf models.
