### ISSUE TITLE
What's the point in TeaVM?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [zeganstyl/thelema-engine#8]
Is TeamVM strategically chosen as way to go or do you plan migration to plain Kotlin JS?

**Comment by zeganstyl** [comment]
TeaVM support was already removed a year ago. Thelema now fully uses MPP and Kotlin JS.

**Comment by dmitrykolesnikovich** [comment]
good to know, better to drop mentioning teavm in readme file

**Comment by dmitrykolesnikovich** [comment]
Good to know. In general is "production-ready" quality of engine is the biggest concern now or do you have another kind of motivation?

**Comment by zeganstyl** [comment]
Thanks for the mention (TeaVM link). Fixed.
Engine is not production ready now.
I want 3d engine on Kotlin. This is my primary hobby project.

**Comment by zeganstyl** [comment]
I want to make some simple 3d game to show, that engine works (and fix engine bugs in parallel). I think I will do it in the next few months.

**Comment by dmitrykolesnikovich** [comment]
I want to refactor your code to show some best practice in making game engine more composable than it is now. I want to use patterns from my game engine https://github.com/featurea/engine. Because making game engine is very huge topic it's good idea to divide it logical in parts - 1) engine itself and 2) technical demos. Because our technology stacks are similar is it interesting to you to make such a collaboration? (I will go with engine itself).

**Comment by zeganstyl** [comment]
Yes, it will be interesting to collaborate.

> I want to refactor your code to show some best practice in making game engine more composable than it is now.

You mean, split Thelema core into separate gradle modules like in KorGE ?

**Comment by zeganstyl** [comment]
How can I build your Featurea engine and run some samples/demos ?

**Comment by dmitrykolesnikovich** [comment]
Yes, I mean splitting Thelema into separate Gradle modules. I am doing it now in my spare time, it will take me two weekends. 

I will add Featurea demos later, may be in a week or two. 

Regarding my collaboration offer I have some more concrete details that I would like to discuss in DM if you will.

**Comment by zeganstyl** [comment]
Yes, you can contact me by email, telegram, or something else.
